version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/secure-file-sharing
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_PATH=uploads/
      - MAX_FILE_SIZE=10485760
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=secure-file-sharing
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
